In [1]:
from pyaccelerator.elements import Drift
from pyaccelerator.elements import QuadrupoleThin
from pyaccelerator import Lattice
from pyaccelerator.utils import to_twiss, to_v_vec, to_phase_coord

import numpy as np

In [2]:
to_v_vec([1,2,3,4])

array([[1],
       [2],
       [3],
       [4]])

In [3]:
to_phase_coord([1,2, 1])

array([[1],
       [2],
       [1]])

In [4]:
to_twiss([1,0,1])

array([[1],
       [0],
       [1]])

In [5]:
to_twiss([1, 0 , None])

array([[1.],
       [0.],
       [1.]])

In [6]:
to_twiss(np.array([1,0,1]))

array([[1],
       [0],
       [1]])

In [7]:
drift = Drift(10)
quad_f = QuadrupoleThin(1)
quad_d = QuadrupoleThin(-1)

In [8]:
quad_f.m

TransferMatrix([[ 1.,  0.,  0.,  0.,  0.],
                [-1.,  1.,  0.,  0.,  0.],
                [ 0.,  0.,  1.,  0.,  0.],
                [ 0.,  0.,  1.,  1.,  0.],
                [ 0.,  0.,  0.,  0.,  1.]])

In [9]:
drift.m

TransferMatrix([[ 1., 10.,  0.,  0.,  0.],
                [ 0.,  1.,  0.,  0.,  0.],
                [ 0.,  0.,  1., 10.,  0.],
                [ 0.,  0.,  0.,  1.,  0.],
                [ 0.,  0.,  0.,  0.,  1.]])

In [10]:
Lattice([quad_d, drift, quad_f]).m

TransferMatrix([[ 11.,  10.,   0.,   0.,   0.],
                [-10.,  -9.,   0.,   0.,   0.],
                [  0.,   0.,  -9.,  10.,   0.],
                [  0.,   0., -10.,  11.,   0.],
                [  0.,   0.,   0.,   0.,   1.]])